/*
 * Java bean class for entity "PRODUCTS" 
 * Created on 2018-04-21 ( Date ISO 2018-04-21 - Time 10:11:31 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.dominio.productdashboardservice.business.transport;

import java.io.Serializable;

/**
 * Java bean for entity "PRODUCTS"
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProductInfo implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Long productId    ; // Id or Primary Key

    private String     category     ;
    private String     productName  ;

    /**
     * Default constructor
     */
    public ProductInfo() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "productId" field value
     * This field is mapped on the database column "PRODUCT_ID" ( type "NUMBER", NotNull : true ) 
     * @param productId
     */
	public void setProductId( Long productId ) {
        this.productId = productId ;
    }
    /**
     * Get the "productId" field value
     * This field is mapped on the database column "PRODUCT_ID" ( type "NUMBER", NotNull : true ) 
     * @return the field value
     */
	public Long getProductId() {
        return this.productId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "category" field value
     * This field is mapped on the database column "CATEGORY" ( type "VARCHAR2", NotNull : false ) 
     * @param category
     */
    public void setCategory( String category ) {
        this.category = category;
    }
    /**
     * Get the "category" field value
     * This field is mapped on the database column "CATEGORY" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Set the "productName" field value
     * This field is mapped on the database column "PRODUCT_NAME" ( type "VARCHAR2", NotNull : false ) 
     * @param productName
     */
    public void setProductName( String productName ) {
        this.productName = productName;
    }
    /**
     * Get the "productName" field value
     * This field is mapped on the database column "PRODUCT_NAME" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getProductName() {
        return this.productName;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(productId);
        sb.append("|");
        sb.append(category);
        sb.append("|");
        sb.append(productName);
        return sb.toString(); 
    } 

}
