/*
 * Created on 2018-04-21 ( Time 11:04:34 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package it.dominio.productservice.data.repository;

import org.springframework.data.repository.CrudRepository;

import it.dominio.productservice.data.entities.Products;



/**
 * Spring JPA Repository for ProductsEntity
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ProductsEntityRepository extends CrudRepository<Products, Long> {


}